### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by binarykitchen** [shama/gaze#114]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch ENOENT
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Gaze._watchDir (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
```

Why it is unhandled? Should I wrap my gaze code in a try-block?

Also, I already have this in my code, but why it is still unhandled?

``` js
process.on('uncaughtException', function(exc) {
    log.fatal('uncaughtException:', exc);
});
```

**Comment by matthew-dean** [comment]
I'm getting this same error with the latest Gaze version.

**Comment by thehappycoder** [comment]
And I get 2016-09-30T03:41:52.655Z - error: uncaughtException: watch /path/to/dir/ ENOENT when I delete watched directory

**Comment by shama** [comment]
@thehappycoder Which version of `gaze`?

**Comment by thehappycoder** [comment]
Latest one at the time of writing.

**Comment by shama** [comment]
Also it should be worth noting, if you don't have at least one event listener:

```js
gaze('*', function () {
  this.on('error', function () {})
})
```

`EventEmitter` in Node.js will throw the error: https://github.com/nodejs/node/blob/master/lib/events.js#L149

Is this what is happening here?
