### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by timoxley** [shama/gaze#173]
Updated to latest nan to get io.js support, but looks like there are some code changes required to get gaze to build on io.js.

```
> npm install nan@latest --save
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
nan@1.5.1 node_modules/nan

> npm install

> gaze@0.6.4 install /Users/timoxley/Projects/libs/gaze
> node build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/pathwatcher/src/main.o
In file included from ../src/main.cc:22:
In file included from ../src/handle_map.h:27:
../src/unsafe_persistent.h:38:38: error: expected ')'
  NAN_INLINE(v8::Persistent<TypeName>* persistent()) {
                                     ^
../src/unsafe_persistent.h:38:13: note: to match this '('
  NAN_INLINE(v8::Persistent<TypeName>* persistent()) {
            ^
../src/unsafe_persistent.h:38:18: error: non-friend class member 'Persistent' cannot have a qualified name
  NAN_INLINE(v8::Persistent<TypeName>* persistent()) {
             ~~~~^
../src/unsafe_persistent.h:38:18: error: C++ requires a type specifier for all declarations
  NAN_INLINE(v8::Persistent<TypeName>* persistent()) {
  ~~~~~~~~~~     ^
../src/unsafe_persistent.h:38:3: error: 'inline' can only appear on functions
  NAN_INLINE(v8::Persistent<TypeName>* persistent()) {
  ^
../node_modules/nan/nan.h:36:21: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE inline __attribute__((always_inline))
                    ^
In file included from ../src/main.cc:22:
In file included from ../src/handle_map.h:27:
../src/unsafe_persistent.h:38:3: warning: 'always_inline' attribute only applies to functions [-Wignored-attributes]
../node_modules/nan/nan.h:36:43: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE inline __attribute__((always_inline))
                                          ^
In file included from ../src/main.cc:22:
In file included from ../src/handle_map.h:27:
../src/unsafe_persistent.h:40:5: error: expected member name or ';' after declaration specifiers
    return handle;
    ^~~~~~
../src/unsafe_persistent.h:29:27: error: member initializer 'value' does not name a non-static data member or base class
  NanUnsafePersistent() : value(0) { }
                          ^~~~~~~~
../src/unsafe_persistent.h:31:5: error: use of undeclared identifier 'value'
    value = handle->ClearAndLeak();
    ^
../src/unsafe_persistent.h:34:41: error: use of undeclared identifier 'nan_isolate'
    v8::Persistent<TypeName> persistent(nan_isolate, handle);
                                        ^
../src/unsafe_persistent.h:35:5: error: use of undeclared identifier 'value'
    value = persistent.ClearAndLeak();
    ^
../src/unsafe_persistent.h:41:4: error: expected ';' after class
  }
   ^
   ;
../src/unsafe_persistent.h:43:14: error: expected unqualified-id
  NAN_INLINE(void Dispose()) {
             ^
../src/unsafe_persistent.h:43:14: error: expected ')'
../src/unsafe_persistent.h:43:13: note: to match this '('
  NAN_INLINE(void Dispose()) {
            ^
../src/unsafe_persistent.h:48:14: error: expected unqualified-id
  NAN_INLINE(void Clear()) {
             ^
../src/unsafe_persistent.h:48:14: error: expected ')'
../src/unsafe_persistent.h:48:13: note: to match this '('
  NAN_INLINE(void Clear()) {
            ^
../src/unsafe_persistent.h:52:24: error: use of undeclared identifier 'TypeName'; did you mean 'typename'?
  NAN_INLINE(v8::Local<TypeName> NewLocal()) {
                       ^~~~~~~~
                       typename
../src/unsafe_persistent.h:52:32: error: expected a qualified name after 'typename'
  NAN_INLINE(v8::Local<TypeName> NewLocal()) {
                               ^
../src/unsafe_persistent.h:52:32: error: expected a type
../src/unsafe_persistent.h:52:34: error: C++ requires a type specifier for all declarations
  NAN_INLINE(v8::Local<TypeName> NewLocal()) {
  ~~~~~~~~~~                     ^
../src/unsafe_persistent.h:53:22: error: use of undeclared identifier 'TypeName'; did you mean 'typename'?
    return v8::Local<TypeName>::New(nan_isolate, *persistent());
                     ^~~~~~~~
                     typename
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/timoxley/Projects/libs/gaze
gyp ERR! node -v v1.0.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v1.0.2
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE
npm ERR! gaze@0.6.4 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gaze@0.6.4 install script 'node build.js'.
npm ERR! This is most likely a problem with the gaze package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gaze
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/timoxley/Projects/libs/gaze/npm-debug.log
```

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by shama** [comment]
Thanks! I attempted to quick update for io.js when it was release but ran into the same issue. 

[navelgazer](https://github.com/shama/navelgazer) which already has node v0.11 support will replace the native code here, so I'll work on io.js support for gaze over there.

**Comment by ai** [comment]
Travis CI added `iojs` annd `nodejs 0.12` support today

**Comment by ai** [comment]
`node.js 0.12` has same issue.

**Comment by egasimus** [comment]
Looking forward to seeing this fixed.

**Comment by arikon** [comment]
:+1: for this

**Comment by wesleytodd** [comment]
Assuming this is why I cannot run `node-sass --watch` with io.  Any word on this?  I am not a C dev or I would try to figure it out myself.  Any recommendations are welcome so I can get this fixed for https://github.com/sass/node-sass/pull/782

**Comment by jeffbski** [comment]
Yes, this appears to still be an issue with gaze@0.6.4 on io@1.6.4 and node@0.12.0. I would like this to fix the emacs issue mentioned above.

**Comment by jeffbski** [comment]
browserSync will need to use the latest gaze when it compiles on node@0.12 and iojs.

**Comment by shama** [comment]
This lib no longer uses native addons.
