### ISSUE TITLE
Why npm isn't updated yet?

### ISSUE THREAD

**Issue by zerkms** [shama/gaze#179]
The currently available `v0.5.1` refers to ancient `globule: ~0.1.0` that refers to ancient `lodash: ~1.0.1` which leads to this:

    [14:23:34] TypeError: boolean is not a function
        at Function.isPlainObject (/vagrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:1652:64)
        at Object.globule.find (/vagrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:64:19)
        at Gaze.add (/vagrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:174:19)
        at new Gaze (/vagrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
        at gaze (/vagrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
        at Object.module.exports [as watch] (/vagrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
        at Gulp.watch (/vagrant/node_modules/gulp/index.js:40:14)
        at Gulp.<anonymous> (/vagrant/gulpfile.es6.js:27:10)
        at module.exports (/vagrant/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/vagrant/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

Any chance the newer `gaze` is published?

**Comment by zerkms** [comment]
Btw, my issue was caused by `6to5` :-S

**Comment by shama** [comment]
https://github.com/shama/gaze/issues/178#issuecomment-73743303
