### ISSUE TITLE
add_test.js fails in Ubuntu 14.04

### ISSUE THREAD

**Issue by skinofstars** [shama/gaze#180]
Hi, 

I cloned this repo and ran `npm run test`. It fails on add_test.js, which I think is the first one.

```
Testing add_test.js
add - addLater...(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gaze.addListener (events.js:160:15)
    at Gaze.<anonymous> (/home/kevin/projects/gaze/test/add_test.js:19:15)
    at /home/kevin/projects/gaze/lib/gaze04.js:53:12
    at /home/kevin/projects/gaze/node_modules/nextback/index.js:8:16
    at process._tickCallback (node.js:419:13)
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

... [snip]...

RangeError: Maximum call stack size exceeded
```

Then from npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'pretest', 'test', 'posttest' ]
6 info pretest gaze@0.6.4
7 info test gaze@0.6.4
8 verbose unsafe-perm in lifecycle true
9 info gaze@0.6.4 Failed to exec test script
10 error gaze@0.6.4 test: `grunt nodeunit -v`
10 error Exit status 7
11 error Failed at the gaze@0.6.4 test script.
11 error This is most likely a problem with the gaze package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     grunt nodeunit -v
11 error You can get their info via:
11 error     npm owner ls gaze
11 error There is likely additional logging output above.
12 error System Linux 3.13.0-45-generic
13 error command "/usr/bin/node" "/usr/bin/npm" "run" "test"
14 error cwd /home/kevin/projects/gaze
15 error node -v v0.10.33
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

Thanks,
Kevin

**Comment by skinofstars** [comment]
I should probably mention, I was running tests because `gulp watch`, which has gaze as a dependency, doesn't work in Ubuntu.

**Comment by aymanrady** [comment]
any update on this issue?
