### ISSUE TITLE
gulp has error on 'watch' task

### ISSUE THREAD

**Issue by g0r1v3r4** [shama/gaze#187]
I am running on a VM with Ubuntu 14.04 64 bit - I am encountering the following issue - All seems to work just fine until it hits the 'watch' task - which fails but the error is not very obvious to me - I made sure to have all packages installed properly - but the error still shows - basically my gulp command runs all the way through but the 'watch' task fails.
````
$ gulp
.......
[23:51:33] Starting 'browserSync'...
[23:51:33] Finished 'browserSync' after 605 ms
[23:51:33] Starting 'watch'...
[BS] Reloading Browsers...
[23:51:33] 'watch' errored after 18 ms
[23:51:33] Error: watch ENOSPC
  at errnoException (fs.js:1031:11)
  at FSWatcher.start (fs.js:1063:11)
  at Object.fs.watch (fs.js:1088:11)
  at Gaze._watchDir (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
  at /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
  at iterate (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
  at Object.forEachSeries (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
  at Gaze._initWatched (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
  at Gaze.add (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
  at new Gaze (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
  at gaze (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
  at Object.module.exports [as watch] (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
  at Gulp.watch (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/index.js:35:16)
  at Gulp.<anonymous> (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/gulp/watch.js:17:10)
  at module.exports (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at Gulp.<anonymous> (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/Gulpfile.js:62:8)
  at module.exports (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
  at Gulp.Orchestrator._runTask (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/gulp/build.js:271:14)
  at module.exports (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
  at DestroyableTransform.emit (events.js:117:20)
  at /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:448:13)
````

**Comment by g0r1v3r4** [comment]
I found a solution to the problem - with the following fix- http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc - apparently there's a limitation on the number of files that gulp can watch - so raising the limit helps - however, is there a way to better control this? It seems hacky to up the limit to solve the problem

running this command apparently increase that "watch" max - but I am not too certain how this is being achieved
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by shama** [comment]
Yep, each system has a limit on the number of file descriptors we can open. When you run out with other file operations, you just wait until some free up. Unfortunately with watching files, they all need to be opened simultaneously. So increasing the limit, if needed, is the ideal solution.

Other options are: watch less files or stat poll (but if you're hitting limits, stat polling that many files will likely be very slow).

Closing as wont(cant)fix.
