### ISSUE TITLE
Crashes when watched directory is moved

### ISSUE THREAD

**Issue by oliversalzburg** [shama/gaze#223]
Happens on Windows:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch C:\prj\src\js\layout\dashboard\organizations\ ENOENT
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Gaze._watchDir (C:\prj\node_modules\gaze\lib\gaze.js:289:30)
    at C:\prj\node_modules\gaze\lib\gaze.js:358:10
    at iterate (C:\prj\node_modules\gaze\lib\helper.js:52:5)
    at C:\prj\node_modules\gaze\lib\helper.js:61:11
    at C:\prj\node_modules\gaze\lib\gaze.js:420:5
    at iterate (C:\prj\node_modules\gaze\lib\helper.js:52:5)
    at C:\prj\node_modules\gaze\lib\helper.js:61:11
    at C:\prj\node_modules\gaze\lib\gaze.js:420:5
    at iterate (C:\prj\node_modules\gaze\lib\helper.js:52:5)
    at C:\prj\node_modules\gaze\lib\helper.js:61:11
    at C:\prj\node_modules\gaze\lib\gaze.js:420:5
    at iterate (C:\prj\node_modules\gaze\lib\helper.js:52:5)
    at Object.forEachSeries (C:\prj\node_modules\gaze\lib\helper.js:66:3)
    at Gaze._initWatched (C:\prj\node_modules\gaze\lib\gaze.js:354:10)
    at Gaze._internalAdd (C:\prj\node_modules\gaze\lib\gaze.js:193:10)
    at C:\prj\node_modules\gaze\lib\gaze.js:400:16
    at Array.forEach (native)
    at C:\prj\node_modules\gaze\lib\gaze.js:396:12
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by shama** [comment]
Should be fixed by https://github.com/shama/gaze/commit/264101644d105f010e382e371db4eda0e45cbdfd Please re-open if it continues. Thanks!
