### ISSUE TITLE
Consider using graceful-fs to fix EMFILE error

### ISSUE THREAD

**Issue by rstacruz** [shama/gaze#73]
I'm sure everyone's encountered the dreaded `EMFILE: Too many opened files` error at some point.

The package graceful-fs (https://npmjs.org/package/graceful-fs) is a drop-in replacement for `fs`, where `fs.watch` is reimplemented to queue up retries when errors happen.

Here's an example of a gaze-related error (via gulpjs.com):

```
 ✈  gulp watch
[gulp] Using file /myproject/gulpfile.js
[gulp] Working directory changed to /myproject
[gulp] Running 'watch'...
[gulp] Finished 'watch' in 4.78 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE: Too many opened files.
    at Gaze._handleError (/myproject/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:414:31)
    at Gaze._watchDir (/myproject/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:292:17)
    at /myproject/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:336:10
    at iterate (/myproject/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
```

**Comment by colinmegill** [comment]
@shama is this still an issue? Is there a known fix that isn't increasing the open file limit on the OS?

```
[gulp] Errored 'watchSrc' in 214 μs EMFILE, too many open files './src'

/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/orchestrator/index.js:153
			throw err;
			      ^
Error: EMFILE, too many open files './src'
    at Object.fs.readdirSync (fs.js:654:18)
    at Glob._readdir (/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob/glob.js:577:20)
    at Glob._process (/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob/glob.js:379:15)
    at Glob.iterator (/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob/glob.js:166:10)
    at Array.forEach (native)
    at new Glob (/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob/glob.js:164:22)
    at glob (/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob/glob.js:57:11)
    at Function.globSync [as sync] (/Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob/glob.js:76:10)
    at /Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:77:17
    at /Users/colinmegill/Desktop/epicure/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:32:30
```

**Comment by shama** [comment]
@colinmegill Increasing the open file limit on the OS is the ideal. The limit is basically a security / memory management setting. It should be set by the user (although I've heard the next version of node tries to increase it for the user, since on OSX, the default is very low: 256).

Other options are watch less files or only stat poll (which will likely start burning down your CPU if you're over your EMFILE). We could use fsevents instead of kqueue which can watch entire directory trees with a single file descriptor (only on OSX) but I haven't figured out a way to get consistent file events, so gaze still uses kqueue.

Down the road I might experiment more with fsevents to avoid EMFILE in [navelgazer](https://github.com/shama/navelgazer) but for now, increasing the limit is recommended.

**Comment by colinmegill** [comment]
Thanks man, and happy new year. $ sudo ulimit -n 10480 doesn't actually do
anything for me on OS X 9 (no changes to ulimit -n). Any idea why?

**Comment by colinmegill** [comment]
@shama

**Comment by shama** [comment]
@colinmegill Happy new year to you! Check out this link: http://yabfog.com/blog/2014/10/22/yosemite-upgrade-changes-open-file-limit

**Comment by colinmegill** [comment]
@shama Thanks! Back home and back at it... that did seem to do something.
The livereload process no longer crashes and having added it to my PATH,
this is durable. Seems hacky but I can accept it. In place of crashing, I
now have a geometrically expanding list of errors:

```

[gulp-sane-watch] 1 file changed (index.html)

[gulp] Running 'js'...

[gulp] Finished 'js' in 3.71 ms

[gulp] Running 'html'...

[gulp] Finished 'html' in 399 μs

[gulp] Running 'watchAndReload'...

[gulp] Finished 'watchAndReload' in 164 μs

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-01 01:54 node[694] (CarbonCore.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

```

I looked around and saw some references to sane, so I tried
gulp-sane-watch, but to no avail. Any suggestions? Here's my gulpfile:

```

var gulp = require("gulp");

var browserify = require("browserify");

var concat = require("gulp-concat");

var jsx = require("gulp-jsx");

var source = require("vinyl-source-stream");

var del = require("del");

var reactify = require("reactify");

var livereload = require("gulp-livereload");

var embedlr = require("gulp-embedlr");

var sass = require("gulp-sass");

var path = require("path")

var cssmin = require("gulp-cssmin");

var autoprefixer = require("gulp-autoprefixer");

var saneWatch = require('gulp-sane-watch');



gulp.task("clean", function(cb){

del(["dist"], cb)

});


gulp.task("css", function () {

  return gulp.src("./src/css/main.scss")

    .pipe(sass({errLogToConsole: true}))

    .pipe(autoprefixer())

    .pipe(cssmin())

    .pipe(gulp.dest("./dist"))

    .pipe(livereload());

});


gulp.task("js", function() {

    // Single entry point to browserify

    browserify({

    entries: ["./src/js/main.js"],

    extensions: [".jsx"],

    paths: ["./node_modules", "./src/js"]

    })

    .transform(reactify)

    .bundle()

        .pipe(source("main.js"))

        // if desired, pipe to uglify or other tasks here before writing to
disk

        .pipe(gulp.dest("./dist/"))

        .pipe(livereload());

});


gulp.task("html", function() {

gulp.src("./src/index.html")

        .pipe(embedlr())

.pipe(gulp.dest("./dist/"))

        .pipe(livereload())

})


gulp.task("watchAndReload", function() {

    livereload.listen()

    saneWatch("./src/**/*", function() {

        gulp.start("default");

    });

});


// gulp.task("watchSrc", function() {

//     gulp.watch(["./src/**/*"], ["default"]);

// });


gulp.task("default", ["js", "css", "html", "watchAndReload"])

```

Thanks again!


ᐧ

**Comment by colinmegill** [comment]
Fixed it: 

```
gulp.task("watchAndReload", function() {
    livereload.listen()
    saneWatch("./src/**/*.html", function() {
        gulp.start("html");
    }); 
    saneWatch("./src/**/*.scss", function() {
        gulp.start("css");
    }); 
    saneWatch(["./src/**/*.js","./src/**/*.jsx"], function() {
        gulp.start("js");
    }); 
});
```

While I didn't think **/* would matter, it did :)
